In [ ]:
use of numpy

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
import numpy as np

In [17]:
a = np.array([8,3,4,5,6])
print(a)

[8 3 4 5 6]


In [70]:
a[1:-1,1:-1]=b

In [62]:
a=np.ones([5,5], dtype="int")

In [63]:
b=np.zeros([3,3], dtype="int")

In [66]:
b[1,1]=9

In [67]:
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [73]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [76]:
np.random.randint(12,30,size=(5,4))

array([[25, 21, 22, 29],
       [22, 27, 24, 22],
       [24, 16, 22, 29],
       [20, 13, 20, 18],
       [15, 21, 22, 21]])

In [82]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

In [81]:
reversed_arr

array([5, 4, 3, 2, 1])

In [87]:
a= np.array([[2,3,4],[5,6,7],[8,9,10]])
print (a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [128]:
a=np.ones([8,8], dtype="int")

In [129]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [134]:
a[0:-1:2,0:-1:2]=0

In [135]:
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [136]:
a[1:8:2,1:8:2]=0

In [137]:
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])