### Load in NumPy (remember to pip install numpy first)

In [6]:
import numpy as np

In [118]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### The Basics

In [135]:
a = np.array([8,3,3,4,5],dtype='int8')
print(a)


[8 3 3 4 5]


In [136]:
b = np.array([[9.0,8.0,7.0,8.0],[6.0,5.0,4.0,9.0],[5.5,6.5,7.8,1.0]],dtype="int8")
b

array([[9, 8, 7, 8],
       [6, 5, 4, 9],
       [5, 6, 7, 1]], dtype=int8)

In [137]:
# Get Dimension
a.ndim


1

In [138]:
# Get Shape
b.shape

(3, 4)

In [139]:
# Get Type
b.dtype

dtype('int8')

In [140]:
# Get Size
b.itemsize

1

In [141]:
# Get total size
b.nbytes

12

In [142]:
# Get number of elements
b.size

12

### Accessing/Changing specific elements, rows, columns, etc

In [156]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [147]:
a[0,6]=700

In [162]:
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 75,   9,  80,  11,  85,  13,  14],
       [ 90,   2,  95,   4, 100,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14]])

In [165]:
a[1:-1 , 0:-1:2]=[[75,80,85],[90,95,100]]

In [155]:
a[1,2:-2]

array([10, 11, 12])

In [ ]:
a[1,4]=21

In [ ]:
a[:,2]

In [ ]:
# Get a specific element [r, c]
a[1,4]=19
a

In [26]:
# Get a specific row 
a[: , 0:-1:2]


array([[ 1,  3,  5],
       [ 8, 10, 12]])

In [49]:
# Get a specific column
c=a[:, 2]
c

array([ 3, 10])

In [ ]:
a[: , 4]

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[1 , 1:6:2]

In [ ]:
a[1,5] = 20
a[1,3]=99
a.shape


In [53]:
a[: , 4] = 1000
a

array([[   1,   12,    3,    4, 1000,    6,   71],
       [   8,   12,   10,   11, 1000,   13,   14]])

*3-d example

In [168]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [177]:
b[0,1,0]=455555

In [178]:
b

array([[[   111,     12],
        [455555,    123]],

       [[     5,      6],
        [     7,      8]]])

In [62]:
# Get specific element (work outside in)
b[0,1,0]


3

In [63]:
b[1,1]

array([7, 8])

In [173]:
# replace 
b[0]=[[111,12],[13,123]]


In [69]:
b[:,1]=[[9,9],[8,2]]
b

array([[[111,  12],
        [  9,   9]],

       [[  5,   6],
        [  8,   2]]])

### Initializing Different Types of Arrays

In [180]:
# All 0s matrix
np.zeros((2,3),dtype="int8")

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [183]:
# All 1s matrix
np.ones((2,2),dtype="int16")

array([[1, 1],
       [1, 1]], dtype=int16)

In [192]:
# Any other number
np.full((6,2), 700)


array([[700, 700],
       [700, 700],
       [700, 700],
       [700, 700],
       [700, 700],
       [700, 700]])

In [191]:
# Any other number (full_like)
np.full_like(b, 101)

array([[[101, 101],
        [101, 101]],

       [[101, 101],
        [101, 101]]])

In [193]:
# Random decimal numbers
np.random.rand(4,5)

array([[0.92870259, 0.53116391, 0.66413857, 0.24440045, 0.50062449],
       [0.34702442, 0.07548782, 0.2320754 , 0.34102453, 0.07567504],
       [0.20135615, 0.92963124, 0.10433922, 0.50140413, 0.61373952],
       [0.44772908, 0.37129992, 0.89404839, 0.13279767, 0.82565811]])

In [205]:
# Random Integer values
np.random.randint(1,100,size=(3,3))

array([[36, 54, 32],
       [76, 97, 67],
       [76,  1, 94]])

In [196]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
# Repeat an array
arr = np.array([[[1,2,3]]])
r1 = np.repeat(arr,1)
print(r1)

[1 2 3]


In [206]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [83]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

### Mathematics

In [84]:
import numpy as np
a = np.array([[1,2,3,4],[1,2,3,4]])
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [85]:
a + 2

array([[3, 4, 5, 6],
       [3, 4, 5, 6]])

In [86]:
a - 2

array([[-1,  0,  1,  2],
       [-1,  0,  1,  2]])

In [87]:
a * 2

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [88]:
a / 2

array([[0.5, 1. , 1.5, 2. ],
       [0.5, 1. , 1.5, 2. ]])

In [90]:
b = np.array([[1,0,1,0]])
a + b

array([[2, 2, 4, 4],
       [2, 2, 4, 4]])

In [92]:
a ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

In [93]:
# Take the sin
np.sin(np.radians(90))



1.0

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [96]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [97]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [98]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
np.min(stats,axis=1) #axis=1 means rows and axis=0 means columns

array([1, 4])

In [100]:
np.max(stats, axis=0)


array([4, 5, 6])

In [101]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing Arrays

In [106]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(f"before {before}")


after = before.reshape((1,8))
print(f"after {after}")

before [[1 2 3 4]
 [5 6 7 8]]
after [[1 2 3 4 5 6 7 8]]


In [107]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [114]:
v1 = np.array([1,2,3,4])
v3=np.array([v1,v1,v1,v1])
v3

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [113]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2,h2,h1))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.]])

### Miscellaneous
##### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int16')
print(filedata)

In [ ]:
filedata>50

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


##### Boolean Masking and Advanced Indexing

In [ ]:
((filedata > 50) & (filedata < 100))


In [ ]:
(~(filedata>50)&(filedata<100))

In [ ]:
np.arange(1,10).reshape(3,3)

In [ ]:
a

In [ ]:
a=np.array([[[[1,2],[3,4],[5,6]],[[1,12],[3,14],[5,16]]],[[[1,222],[3,224],[5,226]],[[1,122],[3,124],[5,126]]]])

In [115]:
import time
import numpy as np


In [116]:
a=[i for i in range(10000000)]
b=[i for i in range(10000000)]
c=[]

start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])

print(time.time()-start)

3.0662784576416016


In [117]:
d=np.arange(10000000)
e=np.arange(10000000)
start=time.time()
f=d+e
print(time.time()-start)

0.03614377975463867
