In [27]:
import numpy as np

In [28]:
a=np.array([1,2,3,4,5])
print(a)
np.max(a)

[1 2 3 4 5]


5

In [29]:
np.min(a)

1

In [30]:
np.argmax(a)

4

In [31]:
a=np.array([10,20,30])
np.append(a, [40,50,60,70,80,90])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
a=np.identity(3, dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [62]:
a=np.zeros([4,4], dtype=int)
print(a)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [63]:
a[0,0]=4

In [64]:
a[1,1]=5

In [67]:
a[2,2]=6

In [68]:
a[3,3]=8

In [69]:
a

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [70]:
a=np.identity(4, dtype=int)

In [71]:
b=np.array([4,5,6,8])

In [72]:
a*b

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [73]:
#formula
#(arr[1]-arr(smallest element))/(arr(maximum element)-arr(minimum element))

In [97]:
a=np.array([1, 2, 3, 4, 5], dtype=int)
b=(a - a.min()) / (a.max() - a.min())
print(b)

[0.   0.25 0.5  0.75 1.  ]


In [94]:
np.mean(a)

3.0

In [79]:
a[-1]=np.mean(a)

In [80]:
a

array([1, 2, 3, 4, 3])

In [90]:
arr=np.array([-1, -2, 3, 4, -5, 6])
print(arr)

[-1 -2  3  4 -5  6]


In [91]:
positive_mask = arr > 0
positive_mean = np.mean(arr[positive_mask])
negative_mask = arr < 0
arr[negative_mask] = positive_mean

In [92]:
print (arr)

[4 4 3 4 4 6]
